### ISSUE TITLE
[Feature request] Adding a config to blacklist/whitelist items and food/saturation values for beeing used as ingredient

### ISSUE THREAD

**Issue by ParaMotor** [TheIllusiveC4/CulinaryConstruct#10]
I don't want players to be able to put whole dishes from Pam's Harvestcraft into a sandwich because in my modpack there is CulinaryConstruct as well as Oversaturation. Oversaturation removes the 20 hunger points cap.

With blacklisting/whitelisting food/saturation values I mean something like with just editing one value in the config you'll be able to disable all food that have more hunger points than this value to be put into a sandwich.

**Comment by TheIllusiveC4** [comment]
I'll consider adding in something like this, but I'm not sure I understand the problem with the interaction between this and Oversaturation. A single sandwich will never exceed 10 food value, because if it does then it splits itself up into multiple ones.

**Comment by ParaMotor** [comment]
Oh ok, well then I didn't understand the description. I thought that the mod looks after the maximum food value possible. My last argument for that is now realism...
