### ISSUE TITLE
[Suggestion] Drink Mixer and "meal", for potions, hard as nails recognized drinks and sandwiches.

### ISSUE THREAD

**Issue by Darkmega18** [TheIllusiveC4/CulinaryConstruct#11]
Just a juice bar kinda thing where you put in a container, usually just a bottle of water or purified water (hard as nails), but perhaps with harvestcraft it could become a colorable slushie or juice glass similar to what that has, or even further a manaflask or elven flask from botania to have multiple chugs.

Without hard as nails mostly only potions would go into the drink mixer. You'd place up to 5 drinks or accepted reagents into the drink along with your water/purified water/canteen and it'll mix up a drink that combines the potion effects and thirst restorations of the drinks and adds the effects of the reagents.
The final drinks would come out with up to a maximum of say 3-5 thirst blips restored and would require more bottles to be crafted depending on how many the juice would make, but it'd also carry the effects of potions put into the drinks like your sandwiches do with consumed foods+effects.

Meal Crafter:
Then this block would take food/sandwiches and drinks and would create a placeable food plate that would hold the effects in it and based on saturating values can be rightclicked while in the world a number of times to eat a "bite" from it like a cake, or perhaps as a stretch a bibliocraft plate. and as you eat from it the food would disappear from the plate, but each bite would still carry the effects of the food that was in it like normal.

So one could create a "buff" meal with a nice combined drink and sandwiches or super potent food items and place it somewhere for the team to take a snack of and it would have the effects (possibly reduced in time for balance?) and each bite would give back a percentage based on it's charges of the food/drink value that would've been gained from eating them all at once in a sandwich or drink.

In an RPG pack you could essentially play as a chef class. giving out foods and drinks to keep the party nourished.

**Comment by TheIllusiveC4** [comment]
Something like this has been suggested before. I'm not really sure I want to expand this mod in such a way, but it's something I'm considering. It'd take quite a lot of extra work though, so I might save it for a 1.13 reboot if anything.

**Comment by Darkmega18** [comment]
aww, dang. :V
