### ISSUE TITLE
Suggestion: Add potions to your food

### ISSUE THREAD

**Issue by TheDeviantCrafter** [TheIllusiveC4/CulinaryConstruct#13]
Imagine this. You're doing your thing, eating your normal super filling sandwich made of six bacon cheeseburgers. Each one keeps you full for like an hour.

Then you decide to go to the nether, and you decide to make a choice. Instead of that super filling sandwich you make one containing 3 bacon cheeseburger and 3 fire resistance potions. Now you gain 24 minutes of fire resistance.

Tinkers' is a fantastically balanced mod because you need to make these choices. Do I want speed or durability, do I spend my modifiers on damage or looting? Letting people choose to make a sandwich that's less filling but gives extra buffs would be awesome.

**Comment by TheIllusiveC4** [comment]
Hmm, it's an interesting idea. I don't think I'd make it exactly like how you suggested, but the idea of introducing certain buffs to the mechanic is worth considering.

**Comment by TheDeviantCrafter** [comment]
What don't you like about this specific implementation?

**Comment by TheIllusiveC4** [comment]
Combining drinks (potions) and food together to form a sandwich doesn't seem very intuitive to me. There was another suggestion about making "meals" with both drinks and an entree, which is a little closer to something I might implement if we're talking strictly about adding potion buffs. But I'm not necessarily ready to commit to either idea at all yet, this is all just under consideration.
