### ISSUE TITLE
[Feature request] Bowl station for soups/salads/stews etc.

### ISSUE THREAD

**Issue by WrongWeekend** [TheIllusiveC4/CulinaryConstruct#17]
The standard wooden bowl doesn't have very many uses in vanilla Minecraft, only having 3 specific ingredient combinations it can be used to craft. A bowl filling/mixing mechanic that works like the sandwiches would be a great complement to this mod's sandwiches, and allow a much larger variety of foods that players can craft such as soups, stews, salads, sundaes, snack mixes, and cereals (depending on what the players wish to name their creations).

Advantages compared to sandwiches:
-Easier to make early on (bowls being easier to obtain than bread)
-Reusable base item
-Potentially, ability to use fluid ingredients

Disadvantages compared to sandwiches:
-Lower hunger fulfillment by default (can't eat the bowl; must use more ingredients to match sandwiches)

In reference to issue #10 , perhaps players should also be able to make separate lists for compatible or incompatible sandwich vs bowl ingredients.

**Comment by TheIllusiveC4** [comment]
Hm, okay, I'll consider this. Thanks for listing out some of the pros and cons.

**Comment by Wotzinator** [comment]
how about drinks ?maybe as a integration with TAN

**Comment by TheIllusiveC4** [comment]
I'll consider it, but drinks are a bit of a tricky subject.

**Comment by WrongWeekend** [comment]
Drinks could work like the bowl foods, except using glass bottles instead. The maximum amount of drink ingredients (and therefore maximum healing) could be lower than a bowl or sandwich, but drinks could be able to be consumed much more quickly.

**Comment by cosmicdan** [comment]
> For that purpose, it'd be easier for me to postpone this feature until the 1.13+ port.

Sad face.

Now that Forge for 1.13 is actually out, do you know how simple would it be for you/me to back port those features to 1.12.2? I've not bothered to look at Forge for 1.13 yet.

**Comment by TheIllusiveC4** [comment]
The main concern is that the way I want this feature implemented would likely be a breaking change, so it's not really a matter of complexity or feasibility.

But on the topic of back-porting in general from 1.13, I think it'd be relatively simple for small features. Even for large features it'd simply be more tedious than complex.

**Comment by TheIllusiveC4** [comment]
Implemented in 1.14.4+ versions.
