### ISSUE TITLE
Sandwiches not retaining their names after being created in the Sandwich Station

### ISSUE THREAD

**Issue by Tyaeth** [TheIllusiveC4/CulinaryConstruct#2]
Forge 14.23.4.2708
culinaryconstruct-1.0.0.jar

[Sandwich being created in the Sandwich Station](https://i.imgur.com/Nmgm65f.png)

[Sandwich after being crafted](https://i.imgur.com/kbCjWfr.png)

**Comment by TheIllusiveC4** [comment]
Hm, weird. I definitely tested this and it was working before. I'll get a fix going right away.
