### ISSUE TITLE
[ENH] Baby APIs

### ISSUE THREAD

**Issue by Wabbit0101** [TheIllusiveC4/CulinaryConstruct#22]
Just some thoughts regarding support of more complex ItemFood implementations:
- an interface (or IMC registration) something like 'getTotalFoodValues' (defaults to getFoodValues for ItemFood/IEdible) so multi-use or other non-standard items can report the correct values to the station
- an interface to support condiments that aren't edible standalone (not an ItemFood) but enrich the target sandwich/food/soup(I've read the comments regarding generalization of the cooking center for 1.13! woohoo!). Sortof like Applecore's IEdible but supports 0 for food value. Might also be just a "passthrough" of a custom string tag for the source ingredient so it can be detected by the source mod's event handler (eg for potion effects, curatives, etc.). I know you're calling the ingredient's onFoodEaten method but that doesn't work for things that override onItemUseFinish instead.
- a config to increase the max food values allowed per sandwich

Really nice mod!

**Comment by TheIllusiveC4** [comment]
Closed:
Config option: 5058b48767d9f5438af2c04595aa25cc61c46823
ICulinaryIngredient API interface: d2a870afa109eba7b1b161486c20b35e6f303c09
AppleCore IEdible integration: f1e3ee40d5c73a8c607c57247117e1022c0d08c4
