### ISSUE TITLE
Sandwiches aren't Counted as Food by Spice of Life

### ISSUE THREAD

**Issue by WenXin20** [TheIllusiveC4/CulinaryConstruct#26]
Forge 14.23.5.2796-1.12.2
[Carrot Edition](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition?gameCategorySlug=mc-mods&projectID=277616) v1.3.3
Culinary Construct v1.3.0

Sandwiches don't seem to be counted as food by Spice of Life or count towards the unique foods eaten. I used the Carrot Edition of the mod, but I assume the regular version is also the same way. 

Also reported to Cazsius/Spice-Of-Life-Carrot-Edition#43

**Comment by TheIllusiveC4** [comment]
I just did some testing and sandwiches are counted as food. I ate a regular apple for testing purposes, which added 1 unique food. Then I made a simple Apple Sandwich, ate that, and then I had a total of 2 unique food. In short, I cannot replicate this bug.

Can you list your steps in detail? Also, I'm not sure this is really related, but it might help to update Culinary Construct to its latest version (1.3.1).

**Comment by WenXin20** [comment]
Ok, it looks like it is counted as food in the newest update.
