### ISSUE TITLE
Feature Request Compatibility with Nutrition mod

### ISSUE THREAD

**Issue by captcookie** [TheIllusiveC4/CulinaryConstruct#27]
I noticed this issue was closed, but after crafting the food it doesn't go towards the buff. Should I ask the nutrition mod author as well?

**Comment by TheIllusiveC4** [comment]
So I just tested this myself and the compatibility does work. I craft a Steak Sandwich which gives me Grain, Protein (3.0%) and, after eating it, the nutrition stats are updated appropriately.

Are you using the 1.3.2 version of Culinary Construct? Can you list out the steps you take in detail?

**Comment by TheIllusiveC4** [comment]
Closing this for now as I have not received a response and the compatibility works as far as I can tell.
