### ISSUE TITLE
Sandwich nesting

### ISSUE THREAD

**Issue by Froggy800** [TheIllusiveC4/CulinaryConstruct#3]
You might want to blacklist sandwiches from being used as ingredients; a player could keep on nesting them and create items with extremely long NBT tags.
Another reason for this is that it's possible to make 6 sandwiches out of 5 if the stats of the ones used as ingredients are good enough.

**Comment by Froggy800** [comment]
I agree with you, I didn't think of the bread as one of the ingredient for some reason...
Also sorry for kinda flooding the issues tracker!

**Comment by TheIllusiveC4** [comment]
No apologies necessaries, it's a good thing! I love getting new issues/suggestions, it gives me the opportunity to polish up the mod as much as possible.
