### ISSUE TITLE
Any item can be inserted into Culinary station

### ISSUE THREAD

**Issue by FirebladeProduction** [TheIllusiveC4/CulinaryConstruct#35]
![BugReport](https://user-images.githubusercontent.com/50214313/77367906-69a39080-6d5b-11ea-8a32-06f9efc45eb0.PNG)

#### Versions (Be specific, do not write "latest"): 
* Culinary Construct: beta2
* Forge: 1.14.4
#### Steps to Reproduce:
1. attach hopper to station
2. add any non food item to the hopper
3. look into station
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
No chrashlogs cause no crash

**Comment by TBiscuit1** [comment]
Just one thing to say NICE X)
