### ISSUE TITLE
Bread (and Bowl) Blacklist 

### ISSUE THREAD

**Issue by TBiscuit1** [TheIllusiveC4/CulinaryConstruct#37]
**Please describe the new feature or change.**
Add a Bread (and Bowl) Blacklist in addition to the bread whitelist

**Please describe why you want this feature.**
For modpacks, (exemple I don't sandwich to be made but I want soup to be made or I want to do a custom sandwich like for exemple cookie that would be used instead of bread)

**Comment by TheIllusiveC4** [comment]
Could you explain in a little bit more detail? As far as my understanding goes, what you want could be accomplished by manipulating the `bread` or `bowl` tags, which are what governs what can be used as breads/bowls.

**Comment by TBiscuit1** [comment]
in both 1.12.2 and 1.14+
Basicly, if I add minecraft:bread to the blacklist, bread wouldn't be able to use the vanilla bread, same goes with bowl, if I add minecraft:bowl, I wouldn't be able to use the vanilla bowl. I just realized with your comment that I could simply remove bread from the bread ore dictionary or tag but a config would be for normal player that don't really know how crafttweaker or datapacks work

**Comment by TheIllusiveC4** [comment]
I guess I'll look into adding something like that for 1.12. But not for 1.14+. Tags are an incredibly powerful vanilla configuration tool and players really should learn how they work if they want to edit configs in general. Plus I'd rather have only one source of truth, rather than multiple.
