### ISSUE TITLE
[1.15.2] Certain modded breads added via config still aren't allowed in the bread slot?

### ISSUE THREAD

**Issue by Coffe-e** [TheIllusiveC4/CulinaryConstruct#38]
#### Versions (Be specific, do not write "latest"):
* Culinary Construct: 2.0.0.1
* Forge: 31.2.19
#### Steps to Reproduce:
1. Put a modded bread listed into the "additional bread items" config, such as buzzier bees' honey bread.
2. Attempt to put it within the bread slot after restarting the game/world.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
N/A

Additional Notes: Oddly enough, Barley and Oat breads from simple farming both work fine with the config

**Comment by TheIllusiveC4** [comment]
You say you're on 1.15.2? The 1.15.2 version doesn't have an additional bread items config, those are handled by data packs now using the bread item tag. Are you using the `culinaryconstruct-server.toml` config file?

**Comment by Coffe-e** [comment]
If that's the case then, i'd like to ask a question if you're up for answering while you're here.
How would I go about handling adding modded breads with datapacks? Is there already a resource I can go to for said datapacks, or would I have to make them myself?

**Comment by TheIllusiveC4** [comment]
I will mention that modders can easily add the necessary tags to their bread, so I'd first recommend going to developers and suggest they add their food to the `bread` tag for automatic compatibility when you encounter one that doesn't work. In the meantime, or if they don't respond, you'd have to make those data packs yourself.

**Comment by Coffe-e** [comment]
Ah, thank you!
