### ISSUE TITLE
Station deletes items when broken

### ISSUE THREAD

**Issue by WenXin20** [TheIllusiveC4/CulinaryConstruct#43]
#### Versions:
* `Culinary Construct: v2.0.0.2`
* `Forge: v1.15.2-31.2.36`
#### Observed Behavior:
- Breaking a station with food in its slots will delete all items if the block is broken.
#### Expected Behavior:
- Food should drop on the ground.
#### Steps to Reproduce:
1. Place food in station
2. Break the station
...

**Comment by TwilightPSN** [comment]
Same issue here on 1.16.4 with version 4.0.0.1
