### ISSUE TITLE
1.14.4

### ISSUE THREAD

**Issue by MakerTim** [TheIllusiveC4/CulinaryConstruct#46]
Wanted to play with your mod in my 1.14.4 pack
but its not in the curse launcher. but when i install it manually it does work, could you add the 1.14.4 tag to your mod in curse forge

**Comment by TheIllusiveC4** [comment]
It's tagged as 1.14.4 already, so I'm not sure what's causing your issue. You should probably report the issue to Curse.

![Screenshot_2020-12-18 Culinary Construct](https://user-images.githubusercontent.com/29991504/102675187-4a505d00-414d-11eb-8f8b-ce635f364901.png)

**Comment by MakerTim** [comment]
Im so sorry! 
I ment 1.16.4

**Comment by TheIllusiveC4** [comment]
Okay, done. It's un-tested on 1.16.4 though, so let me know if you encounter any issues.

**Comment by MakerTim** [comment]
i tested in on my livestream making the pack and after ~25 combinations (including pam's ingredients) all went according to plan / expected behavior
but i will and  thank you!
________________________________
Van: TheIllusiveC4 <notifications@github.com>
Verzonden: zondag 20 december 2020 19:55
Aan: TheIllusiveC4/CulinaryConstruct <CulinaryConstruct@noreply.github.com>
CC: Tim <makertim@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [TheIllusiveC4/CulinaryConstruct] 1.16.4 (#46)


Okay, done. It's un-tested on 1.16.4 though, so let me know if you encounter any issues.
