### ISSUE TITLE
[Features request] Shift clicking bread and ore dictionary

### ISSUE THREAD

**Issue by Froggy800** [TheIllusiveC4/CulinaryConstruct#5]
Shift-clicking bread in the station places the item in one of the the ingredient's slots, unless all the other slots are full; It would make more sense for it to go in the bread slot before any other. This is basically nitpicking on my part, so feel free to ignore this request if it would take an unreasonable amount of time to fulfill.

Another request is the possibility to use all items that are oredicted as _bread_ as such; this would automatically add compatibility with VanillaFoodPantry.

**Comment by TheIllusiveC4** [comment]
I don't fully understand the first part, you'll have to go into detail. Can't you already shift-click bread into the ingredient slots?

I'm working on the oredict stuff as we speak, so that'll be included in the next update.

**Comment by Froggy800** [comment]
Shift-right clicking bread in the station places it in one of the ingredients' slots. It goes in the bread slot only if all the other slots are full.

**Comment by TheIllusiveC4** [comment]
Ah, alright. Yeah, it definitely should be going into the bread slot first, so that's technically a bug. I'll fix it for the next update.
