### ISSUE TITLE
Loaded Baked (Jacket) Potatoes

### ISSUE THREAD

**Issue by DeadlyAccurate** [TheIllusiveC4/CulinaryConstruct#56]
**Please describe the new feature or change.**
The ability to put baked potatoes in the left slot of the Culinary Station and add ingredients to them.

**Please describe why you want this feature.**
Because I keep trying to do it anyway. And this is my favorite cooking mod by a long shot.

**Comment by TheIllusiveC4** [comment]
I'd probably need these baked potatoes to do something special for me to consider this feature. For instance, right now, sandwiches are the basic food combination type while bowls allow adding liquids as well. In the future, I'm considering a cake creation method that allows players to create placeable food as well.

Any additional types needs to have some unique mechanic and function to go along with it, I don't want to create redundant types just for the sake of flavor. Not that it's a bad idea to do so, it's just not what I want to do with the mod.
