### ISSUE TITLE
[Bug]: I can for some reason not find the config files

### ISSUE THREAD

**Issue by Bendoo123** [TheIllusiveC4/CulinaryConstruct#64]
### Minecraft Version

1.18.2

### What happened?

I have played this mod on 1.12.2 as well and it is so much fun to just make insanely OP sandwiches, so I was going to find the config files and, like I did in 1.12.2, make the bread be stackable by a lot. And then... No config files when I tried to do it

### How do you trigger this bug?

1. I open the files of the modpack
2. I open the Config folder
3. I can't seem to find the culinary construct config folder

### Loader

Forge

### Loader Version

Forge - 40.1.80

### Mod Version

culinaryconstruct-forge-1.18.2-4.3.1.0.jar

**Comment by TheIllusiveC4** [comment]
The config file is in your world's `serverconfig` folder.
