### ISSUE TITLE
[Feature]: Placeable bowl of food and pizza blocks

### ISSUE THREAD

**Issue by Darkmega18** [TheIllusiveC4/CulinaryConstruct#67]
### What is the new feature or improvement?

So you've got sandwiches that split large amounts of foods into nice half hunger bar filling snack portions.

You've got meals that combine a bunch of things and just fully combine and hunger values.

Howabout: Food platters and Pizzas.

Food platter: A placeable block that can have up to 10 food items jammed into it.
Once created you get a food platter that when placed can be eaten from. The item should render as a plate of food with a color balanced mass of food within it.
model when placed should try to render it's contained foods all stacked on the plate and as bites are taken out food items on the plate will look like they have bites taken out of them or simply disappear at intervals.
When eating from the food platter the amount of hunger total is split into a large amount of bites based on total food put into it with averaged stats and saturation values + the usual minor bonus for variation. When rightclicked make the foot munching noise and replenish the player. If the player reaches full, play the burping noise and stop eating.
Alternatively, in a similar vein to farmers delight, using a bowl on the plate of food should extract a handful of servings, like say 4 or 5, and combine them into a custom bowl of food similar to your normal bowls of food.
Before finishing and after finishing plates can be picked up and retain their amount of bites within. plates would be made from a circle of clay for an unfinished one, and then fired to get the full plate. Without being used in a meal prep, it should be placeable and accept any food item to be placed on it to display it, like how bibliocraft used to do.
When a plate is used inside the culinary table it should detect it and open/allow the neccessary extra slots.

Pizza would just be a similarly styled placeable food item made by rightclicking "dough" based items from mods onto a pizza board. it starts small and in the center of the block but can be rightclicked with up to 3 more dough to grow the size of the pizza.
Creating a bigger pizza base block makes it accept more food items. This produces a raw pizza block on top that can be accessed to be flavored by one item in each slot. Each dough size increase for the pizza allows 3 items, for a total of 12 ingredient pizza with 2 slots for "sauce" which can be a curated list of sauce items from known mods or potions.

Once placed and filled the pizza should have a button to finish it and pick it up as an object while requiring smelting to cook properly and finalize into a placeable and edible item.

The render should be a square shaped pizza about half a half slab thick with colored ingredients on top. For each 2 ingredients, randomly pick one of their colors and color that type of ingredient on the texture. the sauce also being a combined color of the sauce food items/potions used to make it.

After being cooked, place it down and rightclick to take a slice from the pizza board base as a triangle of pizza in item form to eat as wanted. Breaking the pizza board after placing it down when cooked should immediately break the pizza into it's remaining slices and return the board.

**Comment by TheIllusiveC4** [comment]
It's an interesting idea but this is a little more mechanically complex than I want for Culinary Construct. I will, at some point, implement a placeable type of food item into the mod but it will more likely than not take the form of different types of cakes the player can build, as suggested previously here: https://github.com/illusivesoulworks/culinaryconstruct/issues/50

**Comment by Darkmega18** [comment]
Welp. shoot. alrighty.
