### ISSUE TITLE
[Bug]: Game crashes on startup w/ Fabric Loader 0.14.23

### ISSUE THREAD

**Issue by 0Energy** [TheIllusiveC4/CulinaryConstruct#68]
### Minecraft Version

1.20.1

### What happened?

The game doesn't start with the newest build of Fabric Loader v0.14.23. Having just the loader, the API and the Culinary Construct makes the game crash on startup.

### How do you trigger this bug?

1. Install Fabric Loader v0.14.23 + API + Culinary Construct
2. Start the game
3. BOOM!

### Loader

Fabric

### Loader Version

Fabric - 0.14.23

### API Version

Fabric API 0.90.0

### Mod Version

Culinary Construct 5.2.0+1.20.1

### Relevant Log Outputs

https://gist.github.com/0Energy/8a27689b7672563901e29aeb10ce5b9c

**Comment by 0Energy** [comment]
I just tested it with a number of different versions of the loader, api & mod and found that it's when the loader is 0.14.23 that it crashes like this. It works on Fabric Loader 0.14.22 though.

**Comment by Poopooracoocoo** [comment]
Also see https://github.com/illusivesoulworks/spectrelib/issues/3

**Comment by 0Energy** [comment]
Sweet, thanks for the reference! Closing this then since it's being tracked on the appropriate repository.

**Comment by Poopooracoocoo** [comment]
Could you keep this open to track when this mod will be updated to use the updated version of SpectreLib? :) I subscribed to this issue to find out when it's been updated with the fix
