### ISSUE TITLE
Bread forgot his slot when moved by hopper/any pipe

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [TheIllusiveC4/CulinaryConstruct#7]
I wanted to get a way to make a "factory" of sandwiches and I tried to push the bread into the station, but something went wrong and bread is going to the second slot, where the 5 ingridients needed to be placed.

https://gyazo.com/646779ea12c95e0d808f2f41692415a8

Using Culinary Construct 1.1.0

**Comment by TheIllusiveC4** [comment]
This is a bug, but not in the way you think. The actual intended design is that you shouldn't be able to pipe anything in at all.
